### PR TITLE
Rt point to point directions

### PR DESCRIPTION
**Pull request by roberttaraya**

### CODE REVIEW

**Comment by roberttaraya** [comment]
@gary1410 it's not a spike. i think it is a valid commit, but the feature isn't finished yet, so it definitely shouldn't be merged to master...yet.

**Comment by gary1410** [comment]
Oh nice - thanks for the reply.  @theInternauts Robert turns on his notifications finally and replies! :zap:

**Comment by roberttaraya** [comment]
@gary1410  @theInternauts lol...no i still have notifications "off"...i just happened to reload the page and see your comment ;)

**Comment by theInternauts** [comment]
This PR almost completely obliterated the refactor in PR #4 (submitted almost a month ago).
All the namespace cleanup was lost. Who reviewed this PR?

**Comment by gary1410** [comment]
@roberttaraya didn't merge your PR and work off master.  Not sure what his intention is here but he says it's not mergable?

**Comment by roberttaraya** [comment]
@theInternauts i thought you were smokin crack cuz i remember merging your pull request the other day, at @gary1410 request. BUT, you're right...i think pull request #5 undid your code. I'll fix and bring them back :)

**Comment by theInternauts** [comment]
@roberttaraya no worries. it happens sometimes.  I just melted my local
repo at work :(   git rebase can be deadly, yo.  #TrueStory

**Pull request closed without merging**
